/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ACCESS_H_RPCGEN
#define _ACCESS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ACCESSPROG 0x25201314
#define ACCESSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPEN_DOOR 1
extern  int * open_door_1(int *, CLIENT *);
extern  int * open_door_1_svc(int *, struct svc_req *);
#define CLOSE_DOOR 2
extern  int * close_door_1(int *, CLIENT *);
extern  int * close_door_1_svc(int *, struct svc_req *);
extern int accessprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPEN_DOOR 1
extern  int * open_door_1();
extern  int * open_door_1_svc();
#define CLOSE_DOOR 2
extern  int * close_door_1();
extern  int * close_door_1_svc();
extern int accessprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ACCESS_H_RPCGEN */
