/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TEST 0x20000001
#define PRINT 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTSTR 1
extern  int * printstr_1(char **, CLIENT *);
extern  int * printstr_1_svc(char **, struct svc_req *);
extern int test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTSTR 1
extern  int * printstr_1();
extern  int * printstr_1_svc();
extern int test_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
